version: "3.7"

networks:
    influxdbnet:

volumes:
    influxdb_data:
    chronograf_data:

services:
    influxdb:
        image: influxdb:latest
        volumes:
            - influxdb_data:/var/lib/influxdb
        ports:
            - "8086:8086"
            - "8083:8083"
            - "2003:2003"
        networks:
            - influxdbnet
        restart: always

    chronograf:
        image: chronograf:latest
        volumes:
            - chronograf_data:/var/lib/chronograf
        ports:
            - "8888:8888"
        networks:
            - influxdbnet
        depends_on:
            - influxdb
        entrypoint: 'chronograf --influxdb-url=http://influxdb:8086'
        restart: always

    pyflux:
        build:
            context: "./pyflux"
            dockerfile: Dockerfile
        networks:
            - influxdbnet
        depends_on:
            - influxdb
        restart: always
